// source file automatically generated by BIP tool
// from BIP description out1.bip
// generation date Wed May 14 11:04:04 CEST 2014

#include "out1.bip.h"
CustomerPlugQuorum::CustomerPlugQuorum(const char* name, Compound* holder, int BIPParamid) : Atom(name, holder)  {
    BIP_STATE = S1;
    id = BIPParamid;
    sendToChannel =  new SecondType("sendToChannel", this, proposedValue);
    mPorts.add(sendToChannel);
    recieveFromServer =  new SecondType("recieveFromServer", this, decidedValueS);
    mPorts.add(recieveFromServer);
    sendToClient =  new FirstType("sendToClient", this);
    mPorts.add(sendToClient);
    switchB =  new FirstType("switchB", this);
    mPorts.add(switchB);
    ticker =  new FirstType("ticker", this);
    mPorts.add(ticker);
  }
void CustomerPlugQuorum::initialize(LogicalClock* clock) 
  {
    BIP_Constraint0[0] = NULL;
    BIP_Constraint1[0] = NULL;
    BIP_Constraint2[0] = NULL;
    BIP_Constraint3[0] = NULL;
    BIP_Constraint4[0] = NULL;
    BIP_Constraint5[0] = NULL;
    BIP_Constraint6[0] = NULL;
    BIP_Constraint7[0] = NULL;
    BIP_Constraint8[0] = NULL;
    BIP_Constraint9[0] = NULL;
    BIP_Constraint10[0] = NULL;
    BIP_Constraint11[0] = NULL;
    BIP_TransGuard0 = false;
    BIP_TransGuard1 = false;
    BIP_TransGuard2 = false;
    BIP_TransGuard3 = false;
    BIP_TransGuard4 = false;
    BIP_TransGuard5 = false;
    BIP_TransGuard6 = false;
    BIP_TransGuard7 = false;
    BIP_TransGuard8 = false;
    BIP_TransGuard9 = false;
    BIP_TransGuard10 = false;
    BIP_TransGuard11 = false;
      Port* choice = NULL;
    switch (BIP_STATE) {
      case S1: {
        BIP_TransGuard0 = true;
        if (BIP_TransGuard0) { 
          computePortConstraint(BIP_Constraint0);
        }
        choice = rt_sync(1, sendToChannel, BIP_TransGuard0, BIP_Constraint0[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
      case S2: {
        BIP_TransGuard1 = true;
        BIP_TransGuard2 = true;
        if (BIP_TransGuard1) { 
          computePortConstraint(BIP_Constraint1);
        }
        if (BIP_TransGuard2) { 
          computePortConstraint(BIP_Constraint2);
        }
        choice = rt_sync(2, recieveFromServer, BIP_TransGuard1, BIP_Constraint1[0], ticker, BIP_TransGuard2, BIP_Constraint2[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
      case S3: {
        BIP_TransGuard4 = true;
        BIP_TransGuard5 = true;
        if (BIP_TransGuard4) { 
          computePortConstraint(BIP_Constraint4);
        }
        if (BIP_TransGuard5) { 
          computePortConstraint(BIP_Constraint5);
        }
        choice = rt_sync(2, recieveFromServer, BIP_TransGuard4, BIP_Constraint4[0], ticker, BIP_TransGuard5, BIP_Constraint5[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
      case S4: {
        BIP_TransGuard3 = true;
        BIP_TransGuard11 = true;
        if (BIP_TransGuard3) { 
          computePortConstraint(BIP_Constraint3);
        }
        if (BIP_TransGuard11) { 
          computePortConstraint(BIP_Constraint11);
        }
        choice = rt_sync(2, recieveFromServer, BIP_TransGuard3, BIP_Constraint3[0], ticker, BIP_TransGuard11, BIP_Constraint11[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
      case S5: {
        BIP_TransGuard7 = decidedValue != decidedValueS;
        BIP_TransGuard8 = (decidedValue == decidedValueS);
        if (BIP_TransGuard7) { 
          computePortConstraint(BIP_Constraint7);
        }
        if (BIP_TransGuard8) { 
          computePortConstraint(BIP_Constraint8);
        }
        choice = rt_sync(2, switchB, BIP_TransGuard7, BIP_Constraint7[0], sendToClient, BIP_TransGuard8, BIP_Constraint8[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
      case S6: {
        BIP_TransGuard6 = true;
        if (BIP_TransGuard6) { 
          computePortConstraint(BIP_Constraint6);
        }
        choice = rt_sync(1, switchB, BIP_TransGuard6, BIP_Constraint6[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
      case S7: {
        BIP_TransGuard9 = true;
        if (BIP_TransGuard9) { 
          computePortConstraint(BIP_Constraint9);
        }
        choice = rt_sync(1, ticker, BIP_TransGuard9, BIP_Constraint9[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
      case S8: {
        BIP_TransGuard10 = true;
        if (BIP_TransGuard10) { 
          computePortConstraint(BIP_Constraint10);
        }
        choice = rt_sync(1, ticker, BIP_TransGuard10, BIP_Constraint10[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
    }
  }
void CustomerPlugQuorum::execute(Port* choice) 
  {
      Port* ch = choice;
    while (ch    ) {
      sendToChannel->setSynced(false);
      recieveFromServer->setSynced(false);
      sendToClient->setSynced(false);
      switchB->setSynced(false);
      ticker->setSynced(false);
      sendToChannel->setDominated(false);
      recieveFromServer->setDominated(false);
      sendToClient->setDominated(false);
      switchB->setDominated(false);
      ticker->setDominated(false);
      switch (BIP_STATE) {
        case S1: {
          if ( (sendToChannel == ch)  && BIP_TransGuard0) {
            BIP_STATE = S2;
            BIP_TransGuard1 = true;
            BIP_TransGuard2 = true;
            if (BIP_TransGuard1) { 
              computePortConstraint(BIP_Constraint1);
            }
            if (BIP_TransGuard2) { 
              computePortConstraint(BIP_Constraint2);
            }
            ch = rt_sync(2, recieveFromServer, BIP_TransGuard1, BIP_Constraint1[0], ticker, BIP_TransGuard2, BIP_Constraint2[0]);
          }

          break ;
        }
        case S2: {
          if ( (recieveFromServer == ch)  && BIP_TransGuard1) {
            BIP_STATE = S3;
{
              decidedValue = decidedValueS;
            }
            BIP_TransGuard4 = true;
            BIP_TransGuard5 = true;
            if (BIP_TransGuard4) { 
              computePortConstraint(BIP_Constraint4);
            }
            if (BIP_TransGuard5) { 
              computePortConstraint(BIP_Constraint5);
            }
            ch = rt_sync(2, recieveFromServer, BIP_TransGuard4, BIP_Constraint4[0], ticker, BIP_TransGuard5, BIP_Constraint5[0]);
          }
 else           if ( (ticker == ch)  && BIP_TransGuard2) {
            BIP_STATE = S4;
            BIP_TransGuard3 = true;
            BIP_TransGuard11 = true;
            if (BIP_TransGuard3) { 
              computePortConstraint(BIP_Constraint3);
            }
            if (BIP_TransGuard11) { 
              computePortConstraint(BIP_Constraint11);
            }
            ch = rt_sync(2, recieveFromServer, BIP_TransGuard3, BIP_Constraint3[0], ticker, BIP_TransGuard11, BIP_Constraint11[0]);
          }


          break ;
        }
        case S3: {
          if ( (recieveFromServer == ch)  && BIP_TransGuard4) {
            BIP_STATE = S5;
            BIP_TransGuard7 = decidedValue != decidedValueS;
            BIP_TransGuard8 = (decidedValue == decidedValueS);
            if (BIP_TransGuard7) { 
              computePortConstraint(BIP_Constraint7);
            }
            if (BIP_TransGuard8) { 
              computePortConstraint(BIP_Constraint8);
            }
            ch = rt_sync(2, switchB, BIP_TransGuard7, BIP_Constraint7[0], sendToClient, BIP_TransGuard8, BIP_Constraint8[0]);
          }
 else           if ( (ticker == ch)  && BIP_TransGuard5) {
            BIP_STATE = S6;
            BIP_TransGuard6 = true;
            if (BIP_TransGuard6) { 
              computePortConstraint(BIP_Constraint6);
            }
            ch = rt_sync(1, switchB, BIP_TransGuard6, BIP_Constraint6[0]);
          }


          break ;
        }
        case S4: {
          if ( (recieveFromServer == ch)  && BIP_TransGuard3) {
            BIP_STATE = S6;
{
              decidedValue = decidedValueS;
            }
            BIP_TransGuard6 = true;
            if (BIP_TransGuard6) { 
              computePortConstraint(BIP_Constraint6);
            }
            ch = rt_sync(1, switchB, BIP_TransGuard6, BIP_Constraint6[0]);
          }
 else           if ( (ticker == ch)  && BIP_TransGuard11) {
            BIP_STATE = S4;
            BIP_TransGuard3 = true;
            BIP_TransGuard11 = true;
            if (BIP_TransGuard3) { 
              computePortConstraint(BIP_Constraint3);
            }
            if (BIP_TransGuard11) { 
              computePortConstraint(BIP_Constraint11);
            }
            ch = rt_sync(2, recieveFromServer, BIP_TransGuard3, BIP_Constraint3[0], ticker, BIP_TransGuard11, BIP_Constraint11[0]);
          }


          break ;
        }
        case S5: {
          if ( (switchB == ch)  && BIP_TransGuard7) {
            BIP_STATE = S8;
{
              decidedValue = proposedValue;
            }
            BIP_TransGuard10 = true;
            if (BIP_TransGuard10) { 
              computePortConstraint(BIP_Constraint10);
            }
            ch = rt_sync(1, ticker, BIP_TransGuard10, BIP_Constraint10[0]);
          }
 else           if ( (sendToClient == ch)  && BIP_TransGuard8) {
            BIP_STATE = S7;
            BIP_TransGuard9 = true;
            if (BIP_TransGuard9) { 
              computePortConstraint(BIP_Constraint9);
            }
            ch = rt_sync(1, ticker, BIP_TransGuard9, BIP_Constraint9[0]);
          }


          break ;
        }
        case S6: {
          if ( (switchB == ch)  && BIP_TransGuard6) {
            BIP_STATE = S8;
            BIP_TransGuard10 = true;
            if (BIP_TransGuard10) { 
              computePortConstraint(BIP_Constraint10);
            }
            ch = rt_sync(1, ticker, BIP_TransGuard10, BIP_Constraint10[0]);
          }

          break ;
        }
        case S7: {
          if ( (ticker == ch)  && BIP_TransGuard9) {
            BIP_STATE = S7;
            BIP_TransGuard9 = true;
            if (BIP_TransGuard9) { 
              computePortConstraint(BIP_Constraint9);
            }
            ch = rt_sync(1, ticker, BIP_TransGuard9, BIP_Constraint9[0]);
          }

          break ;
        }
        case S8: {
          if ( (ticker == ch)  && BIP_TransGuard10) {
            BIP_STATE = S8;
            BIP_TransGuard10 = true;
            if (BIP_TransGuard10) { 
              computePortConstraint(BIP_Constraint10);
            }
            ch = rt_sync(1, ticker, BIP_TransGuard10, BIP_Constraint10[0]);
          }

          break ;
        }
      }
    }
  }
plugConnector::plugConnector(const char* name, Compound* holder, int BIPParamid) : Atom(name, holder)  {
    BIP_STATE = start_rcvFServer;
    id = BIPParamid;
    rcvPlug =  new SecondType("rcvPlug", this, proposedValue);
    mPorts.add(rcvPlug);
    sendClient =  new SecondType("sendClient", this, decidedValue);
    mPorts.add(sendClient);
    rcvServer =  new ThirdType("rcvServer", this, clientId, decidedValue);
    mPorts.add(rcvServer);
    SendS1 =  new ThirdType("SendS1", this, clientId, proposedValue);
    mPorts.add(SendS1);
    SendS2 =  new ThirdType("SendS2", this, clientId, proposedValue);
    mPorts.add(SendS2);
    SendS3 =  new ThirdType("SendS3", this, clientId, proposedValue);
    mPorts.add(SendS3);
    SendS4 =  new ThirdType("SendS4", this, clientId, proposedValue);
    mPorts.add(SendS4);
{
      clientId = id;
      server1 = false;
      server2 = false;
      server3 = false;
      server4 = false;
    }
  }
void plugConnector::initialize(LogicalClock* clock) 
  {
    BIP_Constraint0[0] = NULL;
    BIP_Constraint1[0] = NULL;
    BIP_Constraint2[0] = NULL;
    BIP_Constraint3[0] = NULL;
    BIP_Constraint4[0] = NULL;
    BIP_Constraint5[0] = NULL;
    BIP_Constraint6[0] = NULL;
    BIP_Constraint7[0] = NULL;
    BIP_Constraint8[0] = NULL;
    BIP_Constraint9[0] = NULL;
    BIP_Constraint10[0] = NULL;
    BIP_Constraint11[0] = NULL;
    BIP_Constraint12[0] = NULL;
    BIP_Constraint13[0] = NULL;
    BIP_TransGuard0 = false;
    BIP_TransGuard1 = false;
    BIP_TransGuard2 = false;
    BIP_TransGuard3 = false;
    BIP_TransGuard4 = false;
    BIP_TransGuard5 = false;
    BIP_TransGuard6 = false;
    BIP_TransGuard7 = false;
    BIP_TransGuard8 = false;
    BIP_TransGuard9 = false;
    BIP_TransGuard10 = false;
    BIP_TransGuard11 = false;
    BIP_TransGuard12 = false;
    BIP_TransGuard13 = false;
      Port* choice = NULL;
    switch (BIP_STATE) {
      case start_rcvFServer: {
        BIP_TransGuard0 = true;
        BIP_TransGuard2 = true;
        if (BIP_TransGuard0) { 
          computePortConstraint(BIP_Constraint0);
        }
        if (BIP_TransGuard2) { 
          computePortConstraint(BIP_Constraint2);
        }
        choice = rt_sync(2, rcvPlug, BIP_TransGuard0, BIP_Constraint0[0], rcvServer, BIP_TransGuard2, BIP_Constraint2[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
      case sendServer_rcvFServer: {
        BIP_TransGuard3 = true;
        BIP_TransGuard6 =  ! server1;
        BIP_TransGuard8 =  ! server2;
        BIP_TransGuard10 =  ! server3;
        BIP_TransGuard12 =  ! server4;
        if (BIP_TransGuard3) { 
          computePortConstraint(BIP_Constraint3);
        }
        if (BIP_TransGuard6) { 
          computePortConstraint(BIP_Constraint6);
        }
        if (BIP_TransGuard8) { 
          computePortConstraint(BIP_Constraint8);
        }
        if (BIP_TransGuard10) { 
          computePortConstraint(BIP_Constraint10);
        }
        if (BIP_TransGuard12) { 
          computePortConstraint(BIP_Constraint12);
        }
        choice = rt_sync(5, rcvServer, BIP_TransGuard3, BIP_Constraint3[0], SendS1, BIP_TransGuard6, BIP_Constraint6[0], SendS2, BIP_TransGuard8, BIP_Constraint8[0], SendS3, BIP_TransGuard10, BIP_Constraint10[0], SendS4, BIP_TransGuard12, BIP_Constraint12[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
      case start_sendTClient: {
        BIP_TransGuard1 = true;
        BIP_TransGuard4 = true;
        if (BIP_TransGuard1) { 
          computePortConstraint(BIP_Constraint1);
        }
        if (BIP_TransGuard4) { 
          computePortConstraint(BIP_Constraint4);
        }
        choice = rt_sync(2, rcvPlug, BIP_TransGuard1, BIP_Constraint1[0], sendClient, BIP_TransGuard4, BIP_Constraint4[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
      case sendServer_sendTClient: {
        BIP_TransGuard5 = true;
        BIP_TransGuard7 =  ! server1;
        BIP_TransGuard9 =  ! server2;
        BIP_TransGuard11 =  ! server3;
        BIP_TransGuard13 =  ! server4;
        if (BIP_TransGuard5) { 
          computePortConstraint(BIP_Constraint5);
        }
        if (BIP_TransGuard7) { 
          computePortConstraint(BIP_Constraint7);
        }
        if (BIP_TransGuard9) { 
          computePortConstraint(BIP_Constraint9);
        }
        if (BIP_TransGuard11) { 
          computePortConstraint(BIP_Constraint11);
        }
        if (BIP_TransGuard13) { 
          computePortConstraint(BIP_Constraint13);
        }
        choice = rt_sync(5, sendClient, BIP_TransGuard5, BIP_Constraint5[0], SendS1, BIP_TransGuard7, BIP_Constraint7[0], SendS2, BIP_TransGuard9, BIP_Constraint9[0], SendS3, BIP_TransGuard11, BIP_Constraint11[0], SendS4, BIP_TransGuard13, BIP_Constraint13[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
    }
  }
void plugConnector::execute(Port* choice) 
  {
      Port* ch = choice;
    while (ch    ) {
      rcvPlug->setSynced(false);
      sendClient->setSynced(false);
      rcvServer->setSynced(false);
      SendS1->setSynced(false);
      SendS2->setSynced(false);
      SendS3->setSynced(false);
      SendS4->setSynced(false);
      rcvPlug->setDominated(false);
      sendClient->setDominated(false);
      rcvServer->setDominated(false);
      SendS1->setDominated(false);
      SendS2->setDominated(false);
      SendS3->setDominated(false);
      SendS4->setDominated(false);
      switch (BIP_STATE) {
        case start_rcvFServer: {
          if ( (rcvPlug == ch)  && BIP_TransGuard0) {
            BIP_STATE = sendServer_rcvFServer;
            BIP_TransGuard3 = true;
            BIP_TransGuard6 =  ! server1;
            BIP_TransGuard8 =  ! server2;
            BIP_TransGuard10 =  ! server3;
            BIP_TransGuard12 =  ! server4;
            if (BIP_TransGuard3) { 
              computePortConstraint(BIP_Constraint3);
            }
            if (BIP_TransGuard6) { 
              computePortConstraint(BIP_Constraint6);
            }
            if (BIP_TransGuard8) { 
              computePortConstraint(BIP_Constraint8);
            }
            if (BIP_TransGuard10) { 
              computePortConstraint(BIP_Constraint10);
            }
            if (BIP_TransGuard12) { 
              computePortConstraint(BIP_Constraint12);
            }
            ch = rt_sync(5, rcvServer, BIP_TransGuard3, BIP_Constraint3[0], SendS1, BIP_TransGuard6, BIP_Constraint6[0], SendS2, BIP_TransGuard8, BIP_Constraint8[0], SendS3, BIP_TransGuard10, BIP_Constraint10[0], SendS4, BIP_TransGuard12, BIP_Constraint12[0]);
          }
 else           if ( (rcvServer == ch)  && BIP_TransGuard2) {
            BIP_STATE = start_sendTClient;
            BIP_TransGuard1 = true;
            BIP_TransGuard4 = true;
            if (BIP_TransGuard1) { 
              computePortConstraint(BIP_Constraint1);
            }
            if (BIP_TransGuard4) { 
              computePortConstraint(BIP_Constraint4);
            }
            ch = rt_sync(2, rcvPlug, BIP_TransGuard1, BIP_Constraint1[0], sendClient, BIP_TransGuard4, BIP_Constraint4[0]);
          }


          break ;
        }
        case sendServer_rcvFServer: {
          if ( (rcvServer == ch)  && BIP_TransGuard3) {
            BIP_STATE = sendServer_sendTClient;
            BIP_TransGuard5 = true;
            BIP_TransGuard7 =  ! server1;
            BIP_TransGuard9 =  ! server2;
            BIP_TransGuard11 =  ! server3;
            BIP_TransGuard13 =  ! server4;
            if (BIP_TransGuard5) { 
              computePortConstraint(BIP_Constraint5);
            }
            if (BIP_TransGuard7) { 
              computePortConstraint(BIP_Constraint7);
            }
            if (BIP_TransGuard9) { 
              computePortConstraint(BIP_Constraint9);
            }
            if (BIP_TransGuard11) { 
              computePortConstraint(BIP_Constraint11);
            }
            if (BIP_TransGuard13) { 
              computePortConstraint(BIP_Constraint13);
            }
            ch = rt_sync(5, sendClient, BIP_TransGuard5, BIP_Constraint5[0], SendS1, BIP_TransGuard7, BIP_Constraint7[0], SendS2, BIP_TransGuard9, BIP_Constraint9[0], SendS3, BIP_TransGuard11, BIP_Constraint11[0], SendS4, BIP_TransGuard13, BIP_Constraint13[0]);
          }
 else           if ( (SendS1 == ch)  && BIP_TransGuard6) {
            BIP_STATE = sendServer_rcvFServer;
{
              server1 = true;
            }
            BIP_TransGuard3 = true;
            BIP_TransGuard6 =  ! server1;
            BIP_TransGuard8 =  ! server2;
            BIP_TransGuard10 =  ! server3;
            BIP_TransGuard12 =  ! server4;
            if (BIP_TransGuard3) { 
              computePortConstraint(BIP_Constraint3);
            }
            if (BIP_TransGuard6) { 
              computePortConstraint(BIP_Constraint6);
            }
            if (BIP_TransGuard8) { 
              computePortConstraint(BIP_Constraint8);
            }
            if (BIP_TransGuard10) { 
              computePortConstraint(BIP_Constraint10);
            }
            if (BIP_TransGuard12) { 
              computePortConstraint(BIP_Constraint12);
            }
            ch = rt_sync(5, rcvServer, BIP_TransGuard3, BIP_Constraint3[0], SendS1, BIP_TransGuard6, BIP_Constraint6[0], SendS2, BIP_TransGuard8, BIP_Constraint8[0], SendS3, BIP_TransGuard10, BIP_Constraint10[0], SendS4, BIP_TransGuard12, BIP_Constraint12[0]);
          }
 else           if ( (SendS2 == ch)  && BIP_TransGuard8) {
            BIP_STATE = sendServer_rcvFServer;
{
              server2 = true;
            }
            BIP_TransGuard3 = true;
            BIP_TransGuard6 =  ! server1;
            BIP_TransGuard8 =  ! server2;
            BIP_TransGuard10 =  ! server3;
            BIP_TransGuard12 =  ! server4;
            if (BIP_TransGuard3) { 
              computePortConstraint(BIP_Constraint3);
            }
            if (BIP_TransGuard6) { 
              computePortConstraint(BIP_Constraint6);
            }
            if (BIP_TransGuard8) { 
              computePortConstraint(BIP_Constraint8);
            }
            if (BIP_TransGuard10) { 
              computePortConstraint(BIP_Constraint10);
            }
            if (BIP_TransGuard12) { 
              computePortConstraint(BIP_Constraint12);
            }
            ch = rt_sync(5, rcvServer, BIP_TransGuard3, BIP_Constraint3[0], SendS1, BIP_TransGuard6, BIP_Constraint6[0], SendS2, BIP_TransGuard8, BIP_Constraint8[0], SendS3, BIP_TransGuard10, BIP_Constraint10[0], SendS4, BIP_TransGuard12, BIP_Constraint12[0]);
          }
 else           if ( (SendS3 == ch)  && BIP_TransGuard10) {
            BIP_STATE = sendServer_rcvFServer;
{
              server3 = true;
            }
            BIP_TransGuard3 = true;
            BIP_TransGuard6 =  ! server1;
            BIP_TransGuard8 =  ! server2;
            BIP_TransGuard10 =  ! server3;
            BIP_TransGuard12 =  ! server4;
            if (BIP_TransGuard3) { 
              computePortConstraint(BIP_Constraint3);
            }
            if (BIP_TransGuard6) { 
              computePortConstraint(BIP_Constraint6);
            }
            if (BIP_TransGuard8) { 
              computePortConstraint(BIP_Constraint8);
            }
            if (BIP_TransGuard10) { 
              computePortConstraint(BIP_Constraint10);
            }
            if (BIP_TransGuard12) { 
              computePortConstraint(BIP_Constraint12);
            }
            ch = rt_sync(5, rcvServer, BIP_TransGuard3, BIP_Constraint3[0], SendS1, BIP_TransGuard6, BIP_Constraint6[0], SendS2, BIP_TransGuard8, BIP_Constraint8[0], SendS3, BIP_TransGuard10, BIP_Constraint10[0], SendS4, BIP_TransGuard12, BIP_Constraint12[0]);
          }
 else           if ( (SendS4 == ch)  && BIP_TransGuard12) {
            BIP_STATE = sendServer_rcvFServer;
{
              server4 = true;
            }
            BIP_TransGuard3 = true;
            BIP_TransGuard6 =  ! server1;
            BIP_TransGuard8 =  ! server2;
            BIP_TransGuard10 =  ! server3;
            BIP_TransGuard12 =  ! server4;
            if (BIP_TransGuard3) { 
              computePortConstraint(BIP_Constraint3);
            }
            if (BIP_TransGuard6) { 
              computePortConstraint(BIP_Constraint6);
            }
            if (BIP_TransGuard8) { 
              computePortConstraint(BIP_Constraint8);
            }
            if (BIP_TransGuard10) { 
              computePortConstraint(BIP_Constraint10);
            }
            if (BIP_TransGuard12) { 
              computePortConstraint(BIP_Constraint12);
            }
            ch = rt_sync(5, rcvServer, BIP_TransGuard3, BIP_Constraint3[0], SendS1, BIP_TransGuard6, BIP_Constraint6[0], SendS2, BIP_TransGuard8, BIP_Constraint8[0], SendS3, BIP_TransGuard10, BIP_Constraint10[0], SendS4, BIP_TransGuard12, BIP_Constraint12[0]);
          }





          break ;
        }
        case start_sendTClient: {
          if ( (rcvPlug == ch)  && BIP_TransGuard1) {
            BIP_STATE = sendServer_sendTClient;
            BIP_TransGuard5 = true;
            BIP_TransGuard7 =  ! server1;
            BIP_TransGuard9 =  ! server2;
            BIP_TransGuard11 =  ! server3;
            BIP_TransGuard13 =  ! server4;
            if (BIP_TransGuard5) { 
              computePortConstraint(BIP_Constraint5);
            }
            if (BIP_TransGuard7) { 
              computePortConstraint(BIP_Constraint7);
            }
            if (BIP_TransGuard9) { 
              computePortConstraint(BIP_Constraint9);
            }
            if (BIP_TransGuard11) { 
              computePortConstraint(BIP_Constraint11);
            }
            if (BIP_TransGuard13) { 
              computePortConstraint(BIP_Constraint13);
            }
            ch = rt_sync(5, sendClient, BIP_TransGuard5, BIP_Constraint5[0], SendS1, BIP_TransGuard7, BIP_Constraint7[0], SendS2, BIP_TransGuard9, BIP_Constraint9[0], SendS3, BIP_TransGuard11, BIP_Constraint11[0], SendS4, BIP_TransGuard13, BIP_Constraint13[0]);
          }
 else           if ( (sendClient == ch)  && BIP_TransGuard4) {
            BIP_STATE = start_rcvFServer;
            BIP_TransGuard0 = true;
            BIP_TransGuard2 = true;
            if (BIP_TransGuard0) { 
              computePortConstraint(BIP_Constraint0);
            }
            if (BIP_TransGuard2) { 
              computePortConstraint(BIP_Constraint2);
            }
            ch = rt_sync(2, rcvPlug, BIP_TransGuard0, BIP_Constraint0[0], rcvServer, BIP_TransGuard2, BIP_Constraint2[0]);
          }


          break ;
        }
        case sendServer_sendTClient: {
          if ( (sendClient == ch)  && BIP_TransGuard5) {
            BIP_STATE = sendServer_rcvFServer;
            BIP_TransGuard3 = true;
            BIP_TransGuard6 =  ! server1;
            BIP_TransGuard8 =  ! server2;
            BIP_TransGuard10 =  ! server3;
            BIP_TransGuard12 =  ! server4;
            if (BIP_TransGuard3) { 
              computePortConstraint(BIP_Constraint3);
            }
            if (BIP_TransGuard6) { 
              computePortConstraint(BIP_Constraint6);
            }
            if (BIP_TransGuard8) { 
              computePortConstraint(BIP_Constraint8);
            }
            if (BIP_TransGuard10) { 
              computePortConstraint(BIP_Constraint10);
            }
            if (BIP_TransGuard12) { 
              computePortConstraint(BIP_Constraint12);
            }
            ch = rt_sync(5, rcvServer, BIP_TransGuard3, BIP_Constraint3[0], SendS1, BIP_TransGuard6, BIP_Constraint6[0], SendS2, BIP_TransGuard8, BIP_Constraint8[0], SendS3, BIP_TransGuard10, BIP_Constraint10[0], SendS4, BIP_TransGuard12, BIP_Constraint12[0]);
          }
 else           if ( (SendS1 == ch)  && BIP_TransGuard7) {
            BIP_STATE = sendServer_sendTClient;
{
              server1 = true;
            }
            BIP_TransGuard5 = true;
            BIP_TransGuard7 =  ! server1;
            BIP_TransGuard9 =  ! server2;
            BIP_TransGuard11 =  ! server3;
            BIP_TransGuard13 =  ! server4;
            if (BIP_TransGuard5) { 
              computePortConstraint(BIP_Constraint5);
            }
            if (BIP_TransGuard7) { 
              computePortConstraint(BIP_Constraint7);
            }
            if (BIP_TransGuard9) { 
              computePortConstraint(BIP_Constraint9);
            }
            if (BIP_TransGuard11) { 
              computePortConstraint(BIP_Constraint11);
            }
            if (BIP_TransGuard13) { 
              computePortConstraint(BIP_Constraint13);
            }
            ch = rt_sync(5, sendClient, BIP_TransGuard5, BIP_Constraint5[0], SendS1, BIP_TransGuard7, BIP_Constraint7[0], SendS2, BIP_TransGuard9, BIP_Constraint9[0], SendS3, BIP_TransGuard11, BIP_Constraint11[0], SendS4, BIP_TransGuard13, BIP_Constraint13[0]);
          }
 else           if ( (SendS2 == ch)  && BIP_TransGuard9) {
            BIP_STATE = sendServer_sendTClient;
{
              server2 = true;
            }
            BIP_TransGuard5 = true;
            BIP_TransGuard7 =  ! server1;
            BIP_TransGuard9 =  ! server2;
            BIP_TransGuard11 =  ! server3;
            BIP_TransGuard13 =  ! server4;
            if (BIP_TransGuard5) { 
              computePortConstraint(BIP_Constraint5);
            }
            if (BIP_TransGuard7) { 
              computePortConstraint(BIP_Constraint7);
            }
            if (BIP_TransGuard9) { 
              computePortConstraint(BIP_Constraint9);
            }
            if (BIP_TransGuard11) { 
              computePortConstraint(BIP_Constraint11);
            }
            if (BIP_TransGuard13) { 
              computePortConstraint(BIP_Constraint13);
            }
            ch = rt_sync(5, sendClient, BIP_TransGuard5, BIP_Constraint5[0], SendS1, BIP_TransGuard7, BIP_Constraint7[0], SendS2, BIP_TransGuard9, BIP_Constraint9[0], SendS3, BIP_TransGuard11, BIP_Constraint11[0], SendS4, BIP_TransGuard13, BIP_Constraint13[0]);
          }
 else           if ( (SendS3 == ch)  && BIP_TransGuard11) {
            BIP_STATE = sendServer_sendTClient;
{
              server3 = true;
            }
            BIP_TransGuard5 = true;
            BIP_TransGuard7 =  ! server1;
            BIP_TransGuard9 =  ! server2;
            BIP_TransGuard11 =  ! server3;
            BIP_TransGuard13 =  ! server4;
            if (BIP_TransGuard5) { 
              computePortConstraint(BIP_Constraint5);
            }
            if (BIP_TransGuard7) { 
              computePortConstraint(BIP_Constraint7);
            }
            if (BIP_TransGuard9) { 
              computePortConstraint(BIP_Constraint9);
            }
            if (BIP_TransGuard11) { 
              computePortConstraint(BIP_Constraint11);
            }
            if (BIP_TransGuard13) { 
              computePortConstraint(BIP_Constraint13);
            }
            ch = rt_sync(5, sendClient, BIP_TransGuard5, BIP_Constraint5[0], SendS1, BIP_TransGuard7, BIP_Constraint7[0], SendS2, BIP_TransGuard9, BIP_Constraint9[0], SendS3, BIP_TransGuard11, BIP_Constraint11[0], SendS4, BIP_TransGuard13, BIP_Constraint13[0]);
          }
 else           if ( (SendS4 == ch)  && BIP_TransGuard13) {
            BIP_STATE = sendServer_sendTClient;
{
              server4 = true;
            }
            BIP_TransGuard5 = true;
            BIP_TransGuard7 =  ! server1;
            BIP_TransGuard9 =  ! server2;
            BIP_TransGuard11 =  ! server3;
            BIP_TransGuard13 =  ! server4;
            if (BIP_TransGuard5) { 
              computePortConstraint(BIP_Constraint5);
            }
            if (BIP_TransGuard7) { 
              computePortConstraint(BIP_Constraint7);
            }
            if (BIP_TransGuard9) { 
              computePortConstraint(BIP_Constraint9);
            }
            if (BIP_TransGuard11) { 
              computePortConstraint(BIP_Constraint11);
            }
            if (BIP_TransGuard13) { 
              computePortConstraint(BIP_Constraint13);
            }
            ch = rt_sync(5, sendClient, BIP_TransGuard5, BIP_Constraint5[0], SendS1, BIP_TransGuard7, BIP_Constraint7[0], SendS2, BIP_TransGuard9, BIP_Constraint9[0], SendS3, BIP_TransGuard11, BIP_Constraint11[0], SendS4, BIP_TransGuard13, BIP_Constraint13[0]);
          }





          break ;
        }
      }
    }
  }
ServerConnector::ServerConnector(const char* name, Compound* holder, int BIPParamid) : Atom(name, holder)  {
    BIP_STATE = rcvPlug_rcvFServer;
    id = BIPParamid;
    rcvPlugC =  new ThirdType("rcvPlugC", this, clientIdRcv, proposed);
    mPorts.add(rcvPlugC);
    sendServer =  new ThirdType("sendServer", this, clientIdRcv, proposed);
    mPorts.add(sendServer);
    rcvServer =  new ThirdType("rcvServer", this, clientIdSend, decided);
    mPorts.add(rcvServer);
    sendPlug =  new ThirdType("sendPlug", this, clientIdSend, decided);
    mPorts.add(sendPlug);
    loose =  new FirstType("loose", this);
    mPorts.add(loose);
    msglost =  new FirstType("msglost", this);
    mPorts.add(msglost);
  }
void ServerConnector::initialize(LogicalClock* clock) 
  {
    BIP_Constraint0[0] = NULL;
    BIP_Constraint1[0] = NULL;
    BIP_Constraint2[0] = NULL;
    BIP_Constraint3[0] = NULL;
    BIP_Constraint4[0] = NULL;
    BIP_Constraint5[0] = NULL;
    BIP_Constraint6[0] = NULL;
    BIP_Constraint7[0] = NULL;
    BIP_Constraint8[0] = NULL;
    BIP_Constraint9[0] = NULL;
    BIP_Constraint10[0] = NULL;
    BIP_Constraint11[0] = NULL;
    BIP_Constraint12[0] = NULL;
    BIP_Constraint13[0] = NULL;
    BIP_Constraint14[0] = NULL;
    BIP_Constraint15[0] = NULL;
    BIP_TransGuard0 = false;
    BIP_TransGuard1 = false;
    BIP_TransGuard2 = false;
    BIP_TransGuard3 = false;
    BIP_TransGuard4 = false;
    BIP_TransGuard5 = false;
    BIP_TransGuard6 = false;
    BIP_TransGuard7 = false;
    BIP_TransGuard8 = false;
    BIP_TransGuard9 = false;
    BIP_TransGuard10 = false;
    BIP_TransGuard11 = false;
    BIP_TransGuard12 = false;
    BIP_TransGuard13 = false;
    BIP_TransGuard14 = false;
    BIP_TransGuard15 = false;
      Port* choice = NULL;
    switch (BIP_STATE) {
      case rcvPlug_rcvFServer: {
        BIP_TransGuard0 = true;
        BIP_TransGuard10 = true;
        if (BIP_TransGuard0) { 
          computePortConstraint(BIP_Constraint0);
        }
        if (BIP_TransGuard10) { 
          computePortConstraint(BIP_Constraint10);
        }
        choice = rt_sync(2, rcvPlugC, BIP_TransGuard0, BIP_Constraint0[0], rcvServer, BIP_TransGuard10, BIP_Constraint10[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
      case sendTServer_rcvFServer: {
        BIP_TransGuard2 = true;
        BIP_TransGuard6 = true;
        BIP_TransGuard8 = true;
        BIP_TransGuard11 = true;
        if (BIP_TransGuard2) { 
          computePortConstraint(BIP_Constraint2);
        }
        if (BIP_TransGuard6) { 
          computePortConstraint(BIP_Constraint6);
        }
        if (BIP_TransGuard8) { 
          computePortConstraint(BIP_Constraint8);
        }
        if (BIP_TransGuard11) { 
          computePortConstraint(BIP_Constraint11);
        }
        choice = rt_sync(4, loose, BIP_TransGuard2, BIP_Constraint2[0], msglost, BIP_TransGuard6, BIP_Constraint6[0], sendServer, BIP_TransGuard8, BIP_Constraint8[0], rcvServer, BIP_TransGuard11, BIP_Constraint11[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
      case crash_rcvFServer: {
        BIP_TransGuard4 = true;
        BIP_TransGuard12 = true;
        if (BIP_TransGuard4) { 
          computePortConstraint(BIP_Constraint4);
        }
        if (BIP_TransGuard12) { 
          computePortConstraint(BIP_Constraint12);
        }
        choice = rt_sync(2, rcvPlugC, BIP_TransGuard4, BIP_Constraint4[0], rcvServer, BIP_TransGuard12, BIP_Constraint12[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
      case rcvPlug_sendPlugC: {
        BIP_TransGuard1 = true;
        BIP_TransGuard13 = true;
        if (BIP_TransGuard1) { 
          computePortConstraint(BIP_Constraint1);
        }
        if (BIP_TransGuard13) { 
          computePortConstraint(BIP_Constraint13);
        }
        choice = rt_sync(2, rcvPlugC, BIP_TransGuard1, BIP_Constraint1[0], sendPlug, BIP_TransGuard13, BIP_Constraint13[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
      case sendTServer_sendPlugC: {
        BIP_TransGuard3 = true;
        BIP_TransGuard7 = true;
        BIP_TransGuard9 = true;
        BIP_TransGuard14 = true;
        if (BIP_TransGuard3) { 
          computePortConstraint(BIP_Constraint3);
        }
        if (BIP_TransGuard7) { 
          computePortConstraint(BIP_Constraint7);
        }
        if (BIP_TransGuard9) { 
          computePortConstraint(BIP_Constraint9);
        }
        if (BIP_TransGuard14) { 
          computePortConstraint(BIP_Constraint14);
        }
        choice = rt_sync(4, loose, BIP_TransGuard3, BIP_Constraint3[0], msglost, BIP_TransGuard7, BIP_Constraint7[0], sendServer, BIP_TransGuard9, BIP_Constraint9[0], sendPlug, BIP_TransGuard14, BIP_Constraint14[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
      case crash_sendPlugC: {
        BIP_TransGuard5 = true;
        BIP_TransGuard15 = true;
        if (BIP_TransGuard5) { 
          computePortConstraint(BIP_Constraint5);
        }
        if (BIP_TransGuard15) { 
          computePortConstraint(BIP_Constraint15);
        }
        choice = rt_sync(2, rcvPlugC, BIP_TransGuard5, BIP_Constraint5[0], sendPlug, BIP_TransGuard15, BIP_Constraint15[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
    }
  }
void ServerConnector::execute(Port* choice) 
  {
      Port* ch = choice;
    while (ch    ) {
      rcvPlugC->setSynced(false);
      sendServer->setSynced(false);
      rcvServer->setSynced(false);
      sendPlug->setSynced(false);
      loose->setSynced(false);
      msglost->setSynced(false);
      rcvPlugC->setDominated(false);
      sendServer->setDominated(false);
      rcvServer->setDominated(false);
      sendPlug->setDominated(false);
      loose->setDominated(false);
      msglost->setDominated(false);
      switch (BIP_STATE) {
        case rcvPlug_rcvFServer: {
          if ( (rcvPlugC == ch)  && BIP_TransGuard0) {
            BIP_STATE = sendTServer_rcvFServer;
            BIP_TransGuard2 = true;
            BIP_TransGuard6 = true;
            BIP_TransGuard8 = true;
            BIP_TransGuard11 = true;
            if (BIP_TransGuard2) { 
              computePortConstraint(BIP_Constraint2);
            }
            if (BIP_TransGuard6) { 
              computePortConstraint(BIP_Constraint6);
            }
            if (BIP_TransGuard8) { 
              computePortConstraint(BIP_Constraint8);
            }
            if (BIP_TransGuard11) { 
              computePortConstraint(BIP_Constraint11);
            }
            ch = rt_sync(4, loose, BIP_TransGuard2, BIP_Constraint2[0], msglost, BIP_TransGuard6, BIP_Constraint6[0], sendServer, BIP_TransGuard8, BIP_Constraint8[0], rcvServer, BIP_TransGuard11, BIP_Constraint11[0]);
          }
 else           if ( (rcvServer == ch)  && BIP_TransGuard10) {
            BIP_STATE = rcvPlug_sendPlugC;
            BIP_TransGuard1 = true;
            BIP_TransGuard13 = true;
            if (BIP_TransGuard1) { 
              computePortConstraint(BIP_Constraint1);
            }
            if (BIP_TransGuard13) { 
              computePortConstraint(BIP_Constraint13);
            }
            ch = rt_sync(2, rcvPlugC, BIP_TransGuard1, BIP_Constraint1[0], sendPlug, BIP_TransGuard13, BIP_Constraint13[0]);
          }


          break ;
        }
        case sendTServer_rcvFServer: {
          if ( (loose == ch)  && BIP_TransGuard2) {
            BIP_STATE = crash_rcvFServer;
            BIP_TransGuard4 = true;
            BIP_TransGuard12 = true;
            if (BIP_TransGuard4) { 
              computePortConstraint(BIP_Constraint4);
            }
            if (BIP_TransGuard12) { 
              computePortConstraint(BIP_Constraint12);
            }
            ch = rt_sync(2, rcvPlugC, BIP_TransGuard4, BIP_Constraint4[0], rcvServer, BIP_TransGuard12, BIP_Constraint12[0]);
          }
 else           if ( (msglost == ch)  && BIP_TransGuard6) {
            BIP_STATE = rcvPlug_rcvFServer;
            BIP_TransGuard0 = true;
            BIP_TransGuard10 = true;
            if (BIP_TransGuard0) { 
              computePortConstraint(BIP_Constraint0);
            }
            if (BIP_TransGuard10) { 
              computePortConstraint(BIP_Constraint10);
            }
            ch = rt_sync(2, rcvPlugC, BIP_TransGuard0, BIP_Constraint0[0], rcvServer, BIP_TransGuard10, BIP_Constraint10[0]);
          }
 else           if ( (sendServer == ch)  && BIP_TransGuard8) {
            BIP_STATE = rcvPlug_rcvFServer;
            BIP_TransGuard0 = true;
            BIP_TransGuard10 = true;
            if (BIP_TransGuard0) { 
              computePortConstraint(BIP_Constraint0);
            }
            if (BIP_TransGuard10) { 
              computePortConstraint(BIP_Constraint10);
            }
            ch = rt_sync(2, rcvPlugC, BIP_TransGuard0, BIP_Constraint0[0], rcvServer, BIP_TransGuard10, BIP_Constraint10[0]);
          }
 else           if ( (rcvServer == ch)  && BIP_TransGuard11) {
            BIP_STATE = sendTServer_sendPlugC;
            BIP_TransGuard3 = true;
            BIP_TransGuard7 = true;
            BIP_TransGuard9 = true;
            BIP_TransGuard14 = true;
            if (BIP_TransGuard3) { 
              computePortConstraint(BIP_Constraint3);
            }
            if (BIP_TransGuard7) { 
              computePortConstraint(BIP_Constraint7);
            }
            if (BIP_TransGuard9) { 
              computePortConstraint(BIP_Constraint9);
            }
            if (BIP_TransGuard14) { 
              computePortConstraint(BIP_Constraint14);
            }
            ch = rt_sync(4, loose, BIP_TransGuard3, BIP_Constraint3[0], msglost, BIP_TransGuard7, BIP_Constraint7[0], sendServer, BIP_TransGuard9, BIP_Constraint9[0], sendPlug, BIP_TransGuard14, BIP_Constraint14[0]);
          }




          break ;
        }
        case crash_rcvFServer: {
          if ( (rcvPlugC == ch)  && BIP_TransGuard4) {
            BIP_STATE = crash_rcvFServer;
            BIP_TransGuard4 = true;
            BIP_TransGuard12 = true;
            if (BIP_TransGuard4) { 
              computePortConstraint(BIP_Constraint4);
            }
            if (BIP_TransGuard12) { 
              computePortConstraint(BIP_Constraint12);
            }
            ch = rt_sync(2, rcvPlugC, BIP_TransGuard4, BIP_Constraint4[0], rcvServer, BIP_TransGuard12, BIP_Constraint12[0]);
          }
 else           if ( (rcvServer == ch)  && BIP_TransGuard12) {
            BIP_STATE = crash_sendPlugC;
            BIP_TransGuard5 = true;
            BIP_TransGuard15 = true;
            if (BIP_TransGuard5) { 
              computePortConstraint(BIP_Constraint5);
            }
            if (BIP_TransGuard15) { 
              computePortConstraint(BIP_Constraint15);
            }
            ch = rt_sync(2, rcvPlugC, BIP_TransGuard5, BIP_Constraint5[0], sendPlug, BIP_TransGuard15, BIP_Constraint15[0]);
          }


          break ;
        }
        case rcvPlug_sendPlugC: {
          if ( (rcvPlugC == ch)  && BIP_TransGuard1) {
            BIP_STATE = sendTServer_sendPlugC;
            BIP_TransGuard3 = true;
            BIP_TransGuard7 = true;
            BIP_TransGuard9 = true;
            BIP_TransGuard14 = true;
            if (BIP_TransGuard3) { 
              computePortConstraint(BIP_Constraint3);
            }
            if (BIP_TransGuard7) { 
              computePortConstraint(BIP_Constraint7);
            }
            if (BIP_TransGuard9) { 
              computePortConstraint(BIP_Constraint9);
            }
            if (BIP_TransGuard14) { 
              computePortConstraint(BIP_Constraint14);
            }
            ch = rt_sync(4, loose, BIP_TransGuard3, BIP_Constraint3[0], msglost, BIP_TransGuard7, BIP_Constraint7[0], sendServer, BIP_TransGuard9, BIP_Constraint9[0], sendPlug, BIP_TransGuard14, BIP_Constraint14[0]);
          }
 else           if ( (sendPlug == ch)  && BIP_TransGuard13) {
            BIP_STATE = rcvPlug_rcvFServer;
            BIP_TransGuard0 = true;
            BIP_TransGuard10 = true;
            if (BIP_TransGuard0) { 
              computePortConstraint(BIP_Constraint0);
            }
            if (BIP_TransGuard10) { 
              computePortConstraint(BIP_Constraint10);
            }
            ch = rt_sync(2, rcvPlugC, BIP_TransGuard0, BIP_Constraint0[0], rcvServer, BIP_TransGuard10, BIP_Constraint10[0]);
          }


          break ;
        }
        case sendTServer_sendPlugC: {
          if ( (loose == ch)  && BIP_TransGuard3) {
            BIP_STATE = crash_sendPlugC;
            BIP_TransGuard5 = true;
            BIP_TransGuard15 = true;
            if (BIP_TransGuard5) { 
              computePortConstraint(BIP_Constraint5);
            }
            if (BIP_TransGuard15) { 
              computePortConstraint(BIP_Constraint15);
            }
            ch = rt_sync(2, rcvPlugC, BIP_TransGuard5, BIP_Constraint5[0], sendPlug, BIP_TransGuard15, BIP_Constraint15[0]);
          }
 else           if ( (msglost == ch)  && BIP_TransGuard7) {
            BIP_STATE = rcvPlug_sendPlugC;
            BIP_TransGuard1 = true;
            BIP_TransGuard13 = true;
            if (BIP_TransGuard1) { 
              computePortConstraint(BIP_Constraint1);
            }
            if (BIP_TransGuard13) { 
              computePortConstraint(BIP_Constraint13);
            }
            ch = rt_sync(2, rcvPlugC, BIP_TransGuard1, BIP_Constraint1[0], sendPlug, BIP_TransGuard13, BIP_Constraint13[0]);
          }
 else           if ( (sendServer == ch)  && BIP_TransGuard9) {
            BIP_STATE = rcvPlug_sendPlugC;
            BIP_TransGuard1 = true;
            BIP_TransGuard13 = true;
            if (BIP_TransGuard1) { 
              computePortConstraint(BIP_Constraint1);
            }
            if (BIP_TransGuard13) { 
              computePortConstraint(BIP_Constraint13);
            }
            ch = rt_sync(2, rcvPlugC, BIP_TransGuard1, BIP_Constraint1[0], sendPlug, BIP_TransGuard13, BIP_Constraint13[0]);
          }
 else           if ( (sendPlug == ch)  && BIP_TransGuard14) {
            BIP_STATE = sendTServer_rcvFServer;
            BIP_TransGuard2 = true;
            BIP_TransGuard6 = true;
            BIP_TransGuard8 = true;
            BIP_TransGuard11 = true;
            if (BIP_TransGuard2) { 
              computePortConstraint(BIP_Constraint2);
            }
            if (BIP_TransGuard6) { 
              computePortConstraint(BIP_Constraint6);
            }
            if (BIP_TransGuard8) { 
              computePortConstraint(BIP_Constraint8);
            }
            if (BIP_TransGuard11) { 
              computePortConstraint(BIP_Constraint11);
            }
            ch = rt_sync(4, loose, BIP_TransGuard2, BIP_Constraint2[0], msglost, BIP_TransGuard6, BIP_Constraint6[0], sendServer, BIP_TransGuard8, BIP_Constraint8[0], rcvServer, BIP_TransGuard11, BIP_Constraint11[0]);
          }




          break ;
        }
        case crash_sendPlugC: {
          if ( (rcvPlugC == ch)  && BIP_TransGuard5) {
            BIP_STATE = crash_sendPlugC;
            BIP_TransGuard5 = true;
            BIP_TransGuard15 = true;
            if (BIP_TransGuard5) { 
              computePortConstraint(BIP_Constraint5);
            }
            if (BIP_TransGuard15) { 
              computePortConstraint(BIP_Constraint15);
            }
            ch = rt_sync(2, rcvPlugC, BIP_TransGuard5, BIP_Constraint5[0], sendPlug, BIP_TransGuard15, BIP_Constraint15[0]);
          }
 else           if ( (sendPlug == ch)  && BIP_TransGuard15) {
            BIP_STATE = crash_rcvFServer;
            BIP_TransGuard4 = true;
            BIP_TransGuard12 = true;
            if (BIP_TransGuard4) { 
              computePortConstraint(BIP_Constraint4);
            }
            if (BIP_TransGuard12) { 
              computePortConstraint(BIP_Constraint12);
            }
            ch = rt_sync(2, rcvPlugC, BIP_TransGuard4, BIP_Constraint4[0], rcvServer, BIP_TransGuard12, BIP_Constraint12[0]);
          }


          break ;
        }
      }
    }
  }
Server::Server(const char* name, Compound* holder, int BIPParamid) : Atom(name, holder)  {
    BIP_STATE = START;
    id = BIPParamid;
    RcvFromChannel =  new ThirdType("RcvFromChannel", this, ClientId, proposedValue);
    mPorts.add(RcvFromChannel);
    SendToServerC =  new ThirdType("SendToServerC", this, ClientId, decidedValue);
    mPorts.add(SendToServerC);
  }
void Server::initialize(LogicalClock* clock) 
  {
    BIP_Constraint0[0] = NULL;
    BIP_Constraint1[0] = NULL;
    BIP_Constraint2[0] = NULL;
    BIP_TransGuard0 = false;
    BIP_TransGuard1 = false;
    BIP_TransGuard2 = false;
      Port* choice = NULL;
    switch (BIP_STATE) {
      case RECEIVE: {
        BIP_TransGuard2 = true;
        if (BIP_TransGuard2) { 
          computePortConstraint(BIP_Constraint2);
        }
        choice = rt_sync(1, RcvFromChannel, BIP_TransGuard2, BIP_Constraint2[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
      case SEND: {
        BIP_TransGuard1 = true;
        if (BIP_TransGuard1) { 
          computePortConstraint(BIP_Constraint1);
        }
        choice = rt_sync(1, SendToServerC, BIP_TransGuard1, BIP_Constraint1[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
      case START: {
        BIP_TransGuard0 = true;
        if (BIP_TransGuard0) { 
          computePortConstraint(BIP_Constraint0);
        }
        choice = rt_sync(1, RcvFromChannel, BIP_TransGuard0, BIP_Constraint0[0]);
        if (choice) { 
          execute(choice);
        }
        break ;
      }
    }
  }
void Server::execute(Port* choice) 
  {
      Port* ch = choice;
    while (ch    ) {
      RcvFromChannel->setSynced(false);
      SendToServerC->setSynced(false);
      RcvFromChannel->setDominated(false);
      SendToServerC->setDominated(false);
      switch (BIP_STATE) {
        case RECEIVE: {
          if ( (RcvFromChannel == ch)  && BIP_TransGuard2) {
            BIP_STATE = SEND;
            BIP_TransGuard1 = true;
            if (BIP_TransGuard1) { 
              computePortConstraint(BIP_Constraint1);
            }
            ch = rt_sync(1, SendToServerC, BIP_TransGuard1, BIP_Constraint1[0]);
          }

          break ;
        }
        case SEND: {
          if ( (SendToServerC == ch)  && BIP_TransGuard1) {
            BIP_STATE = RECEIVE;
            BIP_TransGuard2 = true;
            if (BIP_TransGuard2) { 
              computePortConstraint(BIP_Constraint2);
            }
            ch = rt_sync(1, RcvFromChannel, BIP_TransGuard2, BIP_Constraint2[0]);
          }

          break ;
        }
        case START: {
          if ( (RcvFromChannel == ch)  && BIP_TransGuard0) {
            BIP_STATE = SEND;
            BIP_TransGuard1 = true;
            if (BIP_TransGuard1) { 
              computePortConstraint(BIP_Constraint1);
            }
            ch = rt_sync(1, SendToServerC, BIP_TransGuard1, BIP_Constraint1[0]);
          }

          break ;
        }
      }
    }
  }
void Singleton::up() 
  {
      Interaction * inter = NULL;
{
    }
  }
void Singleton::dn() 
  {
      Interaction * inter = NULL;
{
    }
  }
bool Singleton::guard() 
  {
    return true;
  }
void SendFromPlugToPlugConnector::up() 
  {
      Interaction * inter = NULL;
  }
void SendFromPlugToPlugConnector::dn() 
  {
      Interaction * inter = NULL;
{
      plugConn->x = customerPlug->x;
    }
  }
bool SendFromPlugToPlugConnector::guard() 
  {
    return true;
  }
void SendFromPlugConToServerCon::up() 
  {
      Interaction * inter = NULL;
  }
void SendFromPlugConToServerCon::dn() 
  {
      Interaction * inter = NULL;
{
      serverConn->x = plugConn->x;
      serverConn->y = plugConn->y;
    }
  }
bool SendFromPlugConToServerCon::guard() 
  {
    return true;
  }
void SendFromServerConnToServer::up() 
  {
      Interaction * inter = NULL;
  }
void SendFromServerConnToServer::dn() 
  {
      Interaction * inter = NULL;
{
      server->x = serverConn->x;
      server->y = serverConn->y;
    }
  }
bool SendFromServerConnToServer::guard() 
  {
    return true;
  }
void SendFromServerToServerC::up() 
  {
      Interaction * inter = NULL;
  }
void SendFromServerToServerC::dn() 
  {
      Interaction * inter = NULL;
{
      serverC->x = server->x;
      serverC->y = server->y;
    }
  }
bool SendFromServerToServerC::guard() 
  {
    return true;
  }
void ServerCPlugC::up() 
  {
      Interaction * inter = NULL;
  }
void ServerCPlugC::dn() 
  {
      Interaction * inter = NULL;
{
      plugC->y = serverC->y;
    }
  }
bool ServerCPlugC::guard() 
  {
    return serverC->x == plugC->x;
  }
void PlugCToPlug::up() 
  {
      Interaction * inter = NULL;
  }
void PlugCToPlug::dn() 
  {
      Interaction * inter = NULL;
{
      plug->x = plugC->x;
    }
  }
bool PlugCToPlug::guard() 
  {
    return true;
  }
Root::Root(const char* name, Compound* holder) : Compound(name, holder)  {
    plug1 =  new CustomerPlugQuorum("plug1", this, 1);
    mComponents.add(plug1);
    plug2 =  new CustomerPlugQuorum("plug2", this, 2);
    mComponents.add(plug2);
    plugC1 =  new plugConnector("plugC1", this, 1);
    mComponents.add(plugC1);
    plugC2 =  new plugConnector("plugC2", this, 2);
    mComponents.add(plugC2);
    serverC1 =  new ServerConnector("serverC1", this, 1);
    mComponents.add(serverC1);
    serverC2 =  new ServerConnector("serverC2", this, 2);
    mComponents.add(serverC2);
    serverC3 =  new ServerConnector("serverC3", this, 3);
    mComponents.add(serverC3);
    serverC4 =  new ServerConnector("serverC4", this, 4);
    mComponents.add(serverC4);
    s1 =  new Server("s1", this, 1);
    mComponents.add(s1);
    s2 =  new Server("s2", this, 2);
    mComponents.add(s2);
    s3 =  new Server("s3", this, 3);
    mComponents.add(s3);
    s4 =  new Server("s4", this, 4);
    mComponents.add(s4);
    sendToClient1 =  new Singleton("sendToClient1", this, false, get_plug1()->get_sendToClient());
    mConnectors.add(sendToClient1);
    switchB1 =  new Singleton("switchB1", this, false, get_plug1()->get_switchB());
    mConnectors.add(switchB1);
    ticker1 =  new Singleton("ticker1", this, false, get_plug1()->get_ticker());
    mConnectors.add(ticker1);
    sendToClient2 =  new Singleton("sendToClient2", this, false, get_plug2()->get_sendToClient());
    mConnectors.add(sendToClient2);
    switchB2 =  new Singleton("switchB2", this, false, get_plug2()->get_switchB());
    mConnectors.add(switchB2);
    ticker2 =  new Singleton("ticker2", this, false, get_plug2()->get_ticker());
    mConnectors.add(ticker2);
    loose1 =  new Singleton("loose1", this, false, get_serverC1()->get_loose());
    mConnectors.add(loose1);
    msglost1 =  new Singleton("msglost1", this, false, get_serverC1()->get_msglost());
    mConnectors.add(msglost1);
    loose2 =  new Singleton("loose2", this, false, get_serverC2()->get_loose());
    mConnectors.add(loose2);
    msglost2 =  new Singleton("msglost2", this, false, get_serverC2()->get_msglost());
    mConnectors.add(msglost2);
    loose3 =  new Singleton("loose3", this, false, get_serverC3()->get_loose());
    mConnectors.add(loose3);
    msglost3 =  new Singleton("msglost3", this, false, get_serverC3()->get_msglost());
    mConnectors.add(msglost3);
    loose4 =  new Singleton("loose4", this, false, get_serverC4()->get_loose());
    mConnectors.add(loose4);
    msglost4 =  new Singleton("msglost4", this, false, get_serverC4()->get_msglost());
    mConnectors.add(msglost4);
    CtoCC1 =  new SendFromPlugToPlugConnector("CtoCC1", this, false, get_plug1()->get_sendToChannel(), get_plugC1()->get_rcvPlug());
    mConnectors.add(CtoCC1);
    CCtoC1 =  new PlugCToPlug("CCtoC1", this, false, get_plugC1()->get_sendClient(), get_plug1()->get_recieveFromServer());
    mConnectors.add(CCtoC1);
    CC1SC1 =  new SendFromPlugConToServerCon("CC1SC1", this, false, get_plugC1()->get_SendS1(), get_serverC1()->get_rcvPlugC());
    mConnectors.add(CC1SC1);
    CC1SC2 =  new SendFromPlugConToServerCon("CC1SC2", this, false, get_plugC1()->get_SendS2(), get_serverC2()->get_rcvPlugC());
    mConnectors.add(CC1SC2);
    CC1SC3 =  new SendFromPlugConToServerCon("CC1SC3", this, false, get_plugC1()->get_SendS3(), get_serverC3()->get_rcvPlugC());
    mConnectors.add(CC1SC3);
    CC1SC4 =  new SendFromPlugConToServerCon("CC1SC4", this, false, get_plugC1()->get_SendS4(), get_serverC4()->get_rcvPlugC());
    mConnectors.add(CC1SC4);
    CtoCC2 =  new SendFromPlugToPlugConnector("CtoCC2", this, false, get_plug2()->get_sendToChannel(), get_plugC2()->get_rcvPlug());
    mConnectors.add(CtoCC2);
    CCtoC2 =  new PlugCToPlug("CCtoC2", this, false, get_plugC2()->get_sendClient(), get_plug2()->get_recieveFromServer());
    mConnectors.add(CCtoC2);
    CC2SC1 =  new SendFromPlugConToServerCon("CC2SC1", this, false, get_plugC2()->get_SendS1(), get_serverC1()->get_rcvPlugC());
    mConnectors.add(CC2SC1);
    CC2SC2 =  new SendFromPlugConToServerCon("CC2SC2", this, false, get_plugC2()->get_SendS2(), get_serverC2()->get_rcvPlugC());
    mConnectors.add(CC2SC2);
    CC2SC3 =  new SendFromPlugConToServerCon("CC2SC3", this, false, get_plugC2()->get_SendS3(), get_serverC3()->get_rcvPlugC());
    mConnectors.add(CC2SC3);
    CC2SC4 =  new SendFromPlugConToServerCon("CC2SC4", this, false, get_plugC2()->get_SendS4(), get_serverC4()->get_rcvPlugC());
    mConnectors.add(CC2SC4);
    StoSC1 =  new SendFromServerToServerC("StoSC1", this, false, get_s1()->get_SendToServerC(), get_serverC1()->get_rcvServer());
    mConnectors.add(StoSC1);
    SCtoS1 =  new SendFromServerConnToServer("SCtoS1", this, false, get_serverC1()->get_sendServer(), get_s1()->get_RcvFromChannel());
    mConnectors.add(SCtoS1);
    SC1CC1 =  new ServerCPlugC("SC1CC1", this, false, get_serverC1()->get_sendPlug(), get_plugC1()->get_rcvServer());
    mConnectors.add(SC1CC1);
    SC1CC2 =  new ServerCPlugC("SC1CC2", this, false, get_serverC1()->get_sendPlug(), get_plugC2()->get_rcvServer());
    mConnectors.add(SC1CC2);
    StoSC2 =  new SendFromServerToServerC("StoSC2", this, false, get_s2()->get_SendToServerC(), get_serverC2()->get_rcvServer());
    mConnectors.add(StoSC2);
    SCtoS2 =  new SendFromServerConnToServer("SCtoS2", this, false, get_serverC2()->get_sendServer(), get_s2()->get_RcvFromChannel());
    mConnectors.add(SCtoS2);
    SC2CC1 =  new ServerCPlugC("SC2CC1", this, false, get_serverC2()->get_sendPlug(), get_plugC1()->get_rcvServer());
    mConnectors.add(SC2CC1);
    SC2CC2 =  new ServerCPlugC("SC2CC2", this, false, get_serverC2()->get_sendPlug(), get_plugC2()->get_rcvServer());
    mConnectors.add(SC2CC2);
    StoSC3 =  new SendFromServerToServerC("StoSC3", this, false, get_s3()->get_SendToServerC(), get_serverC3()->get_rcvServer());
    mConnectors.add(StoSC3);
    SCtoS3 =  new SendFromServerConnToServer("SCtoS3", this, false, get_serverC3()->get_sendServer(), get_s3()->get_RcvFromChannel());
    mConnectors.add(SCtoS3);
    SC3CC1 =  new ServerCPlugC("SC3CC1", this, false, get_serverC3()->get_sendPlug(), get_plugC1()->get_rcvServer());
    mConnectors.add(SC3CC1);
    SC3CC2 =  new ServerCPlugC("SC3CC2", this, false, get_serverC3()->get_sendPlug(), get_plugC2()->get_rcvServer());
    mConnectors.add(SC3CC2);
    StoSC4 =  new SendFromServerToServerC("StoSC4", this, false, get_s4()->get_SendToServerC(), get_serverC4()->get_rcvServer());
    mConnectors.add(StoSC4);
    SCtoS4 =  new SendFromServerConnToServer("SCtoS4", this, false, get_serverC4()->get_sendServer(), get_s4()->get_RcvFromChannel());
    mConnectors.add(SCtoS4);
    SC4CC1 =  new ServerCPlugC("SC4CC1", this, false, get_serverC4()->get_sendPlug(), get_plugC1()->get_rcvServer());
    mConnectors.add(SC4CC1);
    SC4CC2 =  new ServerCPlugC("SC4CC2", this, false, get_serverC4()->get_sendPlug(), get_plugC2()->get_rcvServer());
    mConnectors.add(SC4CC2);
  }
Compound* Compound::Create(int argc, char** argv) 
{
  return  new Root("BIP_Top", NULL);
}
